### ISSUE TITLE
TranslationService expects wrong Translator type

### ISSUE THREAD

**Issue by JKapitein** [yaroslavche/SyliusTranslationPlugin#3]
On newest Sylius:

`request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to Yaroslavche\SyliusTranslationPlugin\Service\TranslationService::__construct() must be an instance of Symfony\Component\Translation\DataCollectorTranslator, instance of Sylius\Bundle\ThemeBundle\Translation\ThemeAwareTranslator given`

And also in the getTranslator.

Can be fixed by omitting type or expecting either ThemeAwareTranslator or Symfony\Contracts\Translation\TranslatorInterface

**Comment by yaroslavche** [comment]
Ok, thanks for your issue. I'll try fix this ASAP.

**Comment by yaroslavche** [comment]
@JKapitein i made fix as you suggested. But can't check right now (and still haven't tests =) ). If you can - please confirm that now is working fine.
